name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you need

      # Install flake8
      - name: Install flake8
        run: python -m pip install flake8

      # Run flake8
      - name: Lint with flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # The options:
        # --count: Print the total number of errors.
        # --select: Comma-separated list of error codes to check.
        # --show-source: Show the source code for each error.
        # --statistics: Print statistics about errors.
